#!/bin/sh
#
# Start/stop baresip
#

PIDFILE=/var/run/jackd.pid

case "$1" in
  start)
	echo "Enable modules..."
        modprobe phy-am335x
        modprobe musb_am335x
        modprobe musb_dsps
        modprobe snd_usb_audio
        sleep 1
	echo "Starting jackd..."
	start-stop-daemon -S -m -b -x /usr/bin/jackd -p $PIDFILE -- -R -P80 -d alsa -d hw:0,0 -r 48000 -n3 -p512
	;;
  stop)
	echo -n "Stopping jackd..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
